# Generated by Django 4.0.3 on 2022-11-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='download.jpg', null=True, upload_to=''),
        ),
    ]
